set_property PACKAGE_PIN W17 [get_ports sys_clk_50M]
set_property PACKAGE_PIN W18 [get_ports sys_rst_n]
set_property PACKAGE_PIN W12 [get_ports {dac_data[0]}]
set_property PACKAGE_PIN V10 [get_ports {dac_data[1]}]
set_property PACKAGE_PIN V9 [get_ports {dac_data[2]}]
set_property PACKAGE_PIN U10 [get_ports {dac_data[3]}]
set_property PACKAGE_PIN U9 [get_ports {dac_data[4]}]
set_property PACKAGE_PIN AA12 [get_ports {dac_data[5]}]
set_property PACKAGE_PIN AB12 [get_ports {dac_data[6]}]
set_property PACKAGE_PIN Y11 [get_ports {dac_data[7]}]
set_property PACKAGE_PIN Y10 [get_ports {dac_data[8]}]
set_property PACKAGE_PIN U12 [get_ports {dac_data[9]}]
set_property PACKAGE_PIN U11 [get_ports {dac_data[10]}]
set_property PACKAGE_PIN AB10 [get_ports {dac_data[11]}]
set_property PACKAGE_PIN AB9 [get_ports {dac_data[12]}]
set_property PACKAGE_PIN AA11 [get_ports {dac_data[13]}]
set_property PACKAGE_PIN AB11 [get_ports {dac_data[14]}]
set_property PACKAGE_PIN V8 [get_ports {dac_data[15]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dac_data[15]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dac_data[14]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dac_data[13]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dac_data[12]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dac_data[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dac_data[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dac_data[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dac_data[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dac_data[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dac_data[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dac_data[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dac_data[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dac_data[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dac_data[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dac_data[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dac_data[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports sys_clk_50M]
set_property IOSTANDARD LVCMOS33 [get_ports sys_rst_n]
set_property PACKAGE_PIN V12 [get_ports dac_dco]
set_property IOSTANDARD LVCMOS33 [get_ports dac_dco]

set_property PACKAGE_PIN AB2 [get_ports {adc_dai[0]}]
set_property PACKAGE_PIN Y4 [get_ports {adc_dai[2]}]
set_property PACKAGE_PIN Y6 [get_ports {adc_dai[4]}]
set_property PACKAGE_PIN AA7 [get_ports {adc_dai[6]}]
set_property PACKAGE_PIN AB5 [get_ports {adc_dai[8]}]
set_property PACKAGE_PIN AA9 [get_ports {adc_dai[10]}]
set_property PACKAGE_PIN AB7 [get_ports {adc_dai[12]}]
set_property PACKAGE_PIN W11 [get_ports {adc_dai[14]}]
set_property PACKAGE_PIN AA4 [get_ports {adc_dai[1]}]
set_property PACKAGE_PIN Y5 [get_ports {adc_dai[3]}]
set_property PACKAGE_PIN AA6 [get_ports {adc_dai[5]}]
set_property PACKAGE_PIN AB4 [get_ports {adc_dai[7]}]
set_property PACKAGE_PIN AA8 [get_ports {adc_dai[9]}]
set_property PACKAGE_PIN AB6 [get_ports {adc_dai[11]}]
set_property PACKAGE_PIN W10 [get_ports {adc_dai[13]}]
set_property PACKAGE_PIN W8 [get_ports {adc_dai[15]}]
set_property IOSTANDARD LVCMOS33 [get_ports {adc_dai[15]}]
set_property IOSTANDARD LVCMOS33 [get_ports {adc_dai[14]}]
set_property IOSTANDARD LVCMOS33 [get_ports {adc_dai[13]}]
set_property IOSTANDARD LVCMOS33 [get_ports {adc_dai[12]}]
set_property IOSTANDARD LVCMOS33 [get_ports {adc_dai[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {adc_dai[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {adc_dai[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {adc_dai[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {adc_dai[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {adc_dai[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {adc_dai[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {adc_dai[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {adc_dai[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {adc_dai[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {adc_dai[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {adc_dai[0]}]

create_clock -period 5.000 -name dac_dco -waveform {0.000 2.500} [get_nets dac_dco]

set_property PACKAGE_PIN AB1 [get_ports adc_clk]
set_property IOSTANDARD LVCMOS33 [get_ports adc_clk]


set_false_path -from [get_pins {u_vio_0/inst/PROBE_OUT_ALL_INST/G_PROBE_OUT[4].PROBE_OUT0_INST/Probe_out_reg[3]/C}] -to [get_pins U_max5885/U_sin_sweep/sweep_en_reg/D]
set_false_path -from [get_pins {u_vio_0/inst/PROBE_OUT_ALL_INST/G_PROBE_OUT[4].PROBE_OUT0_INST/Probe_out_reg[3]/C}] -to [get_pins {U_max5885/U_sin_sweep/STATE_reg[3]/D}]
set_false_path -from [get_pins {u_vio_0/inst/PROBE_OUT_ALL_INST/G_PROBE_OUT[4].PROBE_OUT0_INST/Probe_out_reg[3]/C}] -to [get_pins {U_max5885/U_sin_sweep/STATE_reg[2]/D}]

set_false_path -from [get_pins {u_vio_0/inst/PROBE_OUT_ALL_INST/G_PROBE_OUT[4].PROBE_OUT0_INST/Probe_out_reg[1]/C}] -to [get_pins {U_max5885/U_sin_sweep/config_data_reg_reg[26]_P/CE}]
set_false_path -from [get_pins {u_vio_0/inst/PROBE_OUT_ALL_INST/G_PROBE_OUT[4].PROBE_OUT0_INST/Probe_out_reg[1]/C}] -to [get_pins {U_max5885/U_sin_sweep/config_data_reg_reg[23]_P/CE}]
set_false_path -from [get_pins {u_vio_0/inst/PROBE_OUT_ALL_INST/G_PROBE_OUT[4].PROBE_OUT0_INST/Probe_out_reg[1]/C}] -to [get_pins {U_max5885/U_sin_sweep/config_data_reg_reg[46]_P/CE}]
set_false_path -from [get_pins {u_vio_0/inst/PROBE_OUT_ALL_INST/G_PROBE_OUT[4].PROBE_OUT0_INST/Probe_out_reg[1]/C}] -to [get_pins {U_max5885/U_sin_sweep/config_data_reg_reg[24]_P/CE}]
set_false_path -from [get_pins {u_vio_0/inst/PROBE_OUT_ALL_INST/G_PROBE_OUT[4].PROBE_OUT0_INST/Probe_out_reg[1]/C}] -to [get_pins {U_max5885/U_sin_sweep/config_data_reg_reg[2]_P/CE}]
set_false_path -from [get_pins {u_vio_0/inst/PROBE_OUT_ALL_INST/G_PROBE_OUT[4].PROBE_OUT0_INST/Probe_out_reg[1]/C}] -to [get_pins {U_max5885/U_sin_sweep/config_data_reg_reg[21]_P/CE}]
set_false_path -from [get_pins {u_vio_0/inst/PROBE_OUT_ALL_INST/G_PROBE_OUT[4].PROBE_OUT0_INST/Probe_out_reg[1]/C}] -to [get_pins {U_max5885/U_sin_sweep/config_data_reg_reg[43]_P/CE}]
set_false_path -from [get_pins {u_vio_0/inst/PROBE_OUT_ALL_INST/G_PROBE_OUT[4].PROBE_OUT0_INST/Probe_out_reg[1]/C}] -to [get_pins {U_max5885/U_sin_sweep/config_data_reg_reg[22]_P/CE}]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets dac_dco_OBUF]

set_property PACKAGE_PIN W18 [get_ports key_start]
set_property PACKAGE_PIN V14 [get_ports key_stop]
set_property IOSTANDARD LVCMOS33 [get_ports key_start]
set_property IOSTANDARD LVCMOS33 [get_ports key_stop]
