# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: f:/Xilix/7020/CDelc/LTC2208_MAX5885/TAFU/ltc2208_max5885.srcs/sources_1/ip/floating_point_0/floating_point_0.xci
# IP: The module: 'floating_point_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: f:/Xilix/7020/CDelc/LTC2208_MAX5885/TAFU/ltc2208_max5885.gen/sources_1/ip/floating_point_0/floating_point_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'floating_point_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: f:/Xilix/7020/CDelc/LTC2208_MAX5885/TAFU/ltc2208_max5885.srcs/sources_1/ip/floating_point_0/floating_point_0.xci
# IP: The module: 'floating_point_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: f:/Xilix/7020/CDelc/LTC2208_MAX5885/TAFU/ltc2208_max5885.gen/sources_1/ip/floating_point_0/floating_point_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'floating_point_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
