# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: F:/Xilix/7020/CDelc/LTC2208_MAX5885/TAFU/ltc2208_max5885.srcs/sources_1/ip/fixed2floating_1/fixed2floating_1.xci
# IP: The module: 'fixed2floating_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: f:/Xilix/7020/CDelc/LTC2208_MAX5885/TAFU/ltc2208_max5885.gen/sources_1/ip/fixed2floating_1/fixed2floating_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fixed2floating_1'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: F:/Xilix/7020/CDelc/LTC2208_MAX5885/TAFU/ltc2208_max5885.srcs/sources_1/ip/fixed2floating_1/fixed2floating_1.xci
# IP: The module: 'fixed2floating_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: f:/Xilix/7020/CDelc/LTC2208_MAX5885/TAFU/ltc2208_max5885.gen/sources_1/ip/fixed2floating_1/fixed2floating_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fixed2floating_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
