# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/111.xdc

# IP: ip/fixed2floating_B/fixed2floating_B.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fixed2floating_B || ORIG_REF_NAME==fixed2floating_B} -quiet] -quiet

# IP: ip/dds_compiler_0/dds_compiler_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==dds_compiler_0 || ORIG_REF_NAME==dds_compiler_0} -quiet] -quiet
